global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:9100"]

  - job_name: "api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:3000"]

  - job_name: "worker"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["worker:3001"]
